#   Docker Compose for Run WSO2
#   Test for WSO2-AM 4.1.0
#   Need  "wso2-net" Network for Run this File
#   docker network create --driver bridge --subnet=172.16.50.0/24 wso2-net

version: '3.8'
services:
  mysql:
    image: mysql:5.7.40
    container_name: wso2_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '***'
      MYSQL_DATABASE: 'WSO2AMI_DB'
      MYSQL_USER: 'wso2'
      MYSQL_PASSWORD: '***'
      TZ: Europe/Minsk
    volumes:
      - ./db/scripts:/docker-entrypoint-initdb.d
      - ./db/mysql_idb:/var/lib/mysql
    command: [--ssl=0]
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
      interval: 120s
      timeout: 300s
      retries: 30
      start_period: 300s
    networks:
      wso2-net:
       aliases:
        - wso2-net

  api-manager:
    image: wso2/wso2am
    container_name: wso2_am    
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
      interval: 120s
      timeout: 300s
      start_period: 300s
      retries: 30
    networks:
      wso2-net:
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./apim:/home/wso2carbon/wso2-config-volume
      - ./apim-conf/deployment.toml:/home/wso2carbon/wso2am-4.1.0/repository/conf/deployment.toml
      #- /home/cloud-user/authenticationendpoint.war:/home/wso2carbon/wso2am-4.1.0/repository/deployment/server/webapps/authenticationendpoint.war
    ports:
      - "9443:9443"

networks:
  wso2-net:
    external: true
